// Simple ESM Node server with per-IP daily limits and optional Gemini AI
import http from 'http';
import fs from 'fs';
import path from 'path';
import { GoogleGenAI } from '@google/genai';
import { loadDb, getSession, setSession } from './db.js';

// Lightweight .env loader for local dev (.env.local or .env)
const loadEnvFile = (filename) => {
  try {
    const p = path.resolve(process.cwd(), filename);
    if (!fs.existsSync(p)) return;
    const txt = fs.readFileSync(p, 'utf8');
    for (const line of txt.split(/\r?\n/)) {
      if (!line || line.trim().startsWith('#')) continue;
      const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      const key = m[1];
      let val = m[2];
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith('\'') && val.endsWith('\''))) {
        val = val.slice(1, -1);
      }
      if (process.env[key] == null) process.env[key] = val;
    }
  } catch {}
};

loadEnvFile('.env.local');
loadEnvFile('.env');

const parsePortArg = () => {
  try {
    const args = process.argv.slice(2);
    for (let i = 0; i < args.length; i++) {
      const a = args[i];
      if (a.startsWith('--port=')) {
        const v = Number(a.split('=')[1]);
        if (Number.isFinite(v) && v > 0) return v;
      }
      if (a === '--port' || a === '-p') {
        const next = Number(args[i + 1]);
        if (Number.isFinite(next) && next > 0) return next;
      }
    }
  } catch {}
  return null;
};

const PORT = Number(process.env.PORT) > 0 ? Number(process.env.PORT) : (parsePortArg() ?? 8787);
const MAX_PER_DAY = process.env.MAX_REQUESTS_PER_DAY ? Math.max(1, Number(process.env.MAX_REQUESTS_PER_DAY)) : 5;
const ENABLE_GEMINI = String(process.env.ENABLE_GEMINI || '').toLowerCase() === 'true';
const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

let ai = null;
if (ENABLE_GEMINI && GEMINI_API_KEY) {
  try {
    ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
  } catch (e) {
    console.warn('[server] Failed to init Gemini client:', e);
    ai = null;
  }
}
// No AI backend; responses are generated by simple rules below

// Persistent IP counter { ip: { date: 'YYYY-MM-DD', count: number } }
const COUNTERS_FILE = process.env.COUNTERS_FILE || path.resolve(process.cwd(), 'rate-counters.json');
const counters = new Map();

const loadCounters = () => {
  try {
    if (!fs.existsSync(COUNTERS_FILE)) return;
    const raw = fs.readFileSync(COUNTERS_FILE, 'utf8');
    const obj = JSON.parse(raw || '{}');
    const today = todayKey();
    for (const [ip, state] of Object.entries(obj)) {
      const s = state && typeof state === 'object' ? state : null;
      const date = s?.date;
      const count = Number(s?.count ?? 0);
      counters.set(String(ip), { date: today, count: date === today ? Math.max(0, count) : 0 });
    }
  } catch (e) {
    console.warn('[server] Failed to load counters:', e);
  }
};

const saveCounters = () => {
  try {
    const obj = {};
    for (const [ip, state] of counters.entries()) {
      obj[ip] = state;
    }
    fs.writeFileSync(COUNTERS_FILE, JSON.stringify(obj, null, 2), 'utf8');
  } catch (e) {
    console.warn('[server] Failed to save counters:', e);
  }
};

const todayKey = () => {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

const getClientIp = (req) => {
  const xf = req.headers['x-forwarded-for'];
  if (typeof xf === 'string' && xf.length > 0) return xf.split(',')[0].trim();
  if (Array.isArray(xf) && xf.length > 0) return xf[0];
  return req.socket?.remoteAddress || 'unknown';
};

const allowCORS = (res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
};

// Static file serving (production)
const STATIC_DIR = process.env.STATIC_DIR || path.resolve(process.cwd(), 'dist');
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain; charset=utf-8'
};

const serveStatic = (req, res) => {
  try {
    if (req.method !== 'GET') return false;
    let urlPath = req.url.split('?')[0];
    if (urlPath.startsWith('/api/')) return false; // API handled elsewhere
    if (urlPath === '/') urlPath = '/index.html';
    const safeSegs = urlPath.split('/').filter(Boolean).filter(s => s !== '..');
    const filePath = path.join(STATIC_DIR, ...safeSegs);
    if (!filePath.startsWith(STATIC_DIR)) return false;
    if (!fs.existsSync(filePath)) {
      // SPA fallback to index.html
      const indexPath = path.join(STATIC_DIR, 'index.html');
      if (!fs.existsSync(indexPath)) return false;
      res.writeHead(200, { 'Content-Type': MIME['.html'] });
      res.end(fs.readFileSync(indexPath));
      return true;
    }
    const ext = path.extname(filePath).toLowerCase();
    const type = MIME[ext] || 'application/octet-stream';
    res.writeHead(200, { 'Content-Type': type });
    res.end(fs.readFileSync(filePath));
    return true;
  } catch (e) {
    return false;
  }
};

// Simple rule-based responder (non-AI) for demo purposes
const generateReply = (messages) => {
  // Find last user message
  const reversed = [...messages].reverse();
  const lastUser = reversed.find(m => String(m.role) === 'user');
  const text = String(lastUser?.content || '').toLowerCase();
  if (!text) {
    return 'Halo! Silakan tulis pengeluaran atau minta laporan.';
  }
  // Report intent
  if (text.includes('laporan') || text.includes("report")) {
    return 'Fitur laporan detail belum diaktifkan. Anda bisa tetap mencatat pengeluaran harian.';
  }
  // Expense-like input detection
  const hasAmount = /\d/.test(text) || /rp|idr|dollar|\$/.test(text);
  if (hasAmount) {
    return 'Untuk mencatat pengeluaran, sertakan kategori dan tanggal. Contoh kategori: Makanan, Transportasi, Hiburan, Belanja, Tagihan. Jika tanggal tidak disebutkan, akan dianggap hari ini.';
  }
  // Default help
  return 'Saya aplikasi pencatatan sederhana. Contoh: "Catat pengeluaran 50rb untuk Makanan hari ini" atau minta "laporan bulan ini".';
};

const server = http.createServer(async (req, res) => {
  allowCORS(res);
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }
  if (req.method === 'GET' && req.url === '/api/quota') {
    const ip = getClientIp(req);
    const key = ip || 'unknown';
    const today = todayKey();
    const state = counters.get(key) || { date: today, count: 0 };
    const current = state.date === today ? state.count : 0;
    const remaining = Math.max(0, MAX_PER_DAY - current);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ remaining, limit: MAX_PER_DAY }));
    return;
  }
  // Load session history
  if (req.method === 'POST' && req.url === '/api/session/load') {
    const chunks = [];
    for await (const chunk of req) chunks.push(chunk);
    const bodyRaw = Buffer.concat(chunks).toString('utf8');
    let payload;
    try { payload = JSON.parse(bodyRaw || '{}'); } catch { payload = {}; }
    const sessionId = typeof payload?.sessionId === 'string' ? payload.sessionId : null;
    const data = sessionId ? getSession(sessionId) : [];
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ history: data }));
    return;
  }
  if (req.method !== 'POST' || req.url !== '/api/chat') {
    // try static serving
    if (serveStatic(req, res)) return;
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not found' }));
    return;
  }

  // Rate limit per IP per day
  const ip = getClientIp(req);
  const key = ip || 'unknown';
  const today = todayKey();
  const state = counters.get(key) || { date: today, count: 0 };
  const current = state.date === today ? state.count : 0;
  if (current >= MAX_PER_DAY) {
    res.writeHead(429, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Batas penggunaan harian per jaringan tercapai. Coba lagi besok.' }));
    return;
  }

  // Read body
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const bodyRaw = Buffer.concat(chunks).toString('utf8');
  let payload;
  try {
    payload = JSON.parse(bodyRaw || '{}');
  } catch {
    res.writeHead(400, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Invalid JSON' }));
    return;
  }

  const sessionId = typeof payload?.sessionId === 'string' ? payload.sessionId : null;
  const messages = Array.isArray(payload?.history) ? payload.history : [];
  try {
    // consume one
    counters.set(key, { date: today, count: current + 1 });
    saveCounters();

    // Persist session pre-response (store user msg)
    if (sessionId) {
      try { setSession(sessionId, messages); } catch {}
    }

    let text = '';
    if (ai) {
      try {
        const contents = messages.slice(1).map((m) => ({
          role: String(m.role) === 'user' ? 'user' : 'model',
          parts: [{ text: String(m.content ?? '') }],
        }));
        const response = await ai.models.generateContent({
          model: GEMINI_MODEL,
          contents,
        });
        text = String(response.text || '').trim();
      } catch (e) {
        console.error('[server] gemini error, falling back:', e);
        text = generateReply(messages);
      }
    } else {
      text = generateReply(messages);
    }
    // Append assistant message and persist session if provided
    if (sessionId) {
      try { setSession(sessionId, [...messages, { role: 'assistant', content: text }]); } catch {}
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ text }));
  } catch (err) {
    console.error('[server] chat error:', err);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Failed to get response from the assistant.' }));
  }
});

loadCounters();
loadDb();
server.listen(PORT, () => {
  console.log(`[server] listening on http://localhost:${PORT}`);
});
